# Minimal Jekyll config for testing
title: blank
first_name: two_spoons
email: twospoonstv@gmail.com
description: A simple Jekyll site

url: https://TwoBloodySpoons.github.io
baseurl: /

# Basic theme settings
navbar_fixed: true
footer_fixed: true

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - vendor
  - Gemfile*
  - LICENSE
  - README.md

# Basic plugins only
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

# Pagination
pagination:
  enabled: true

# Archive settings
jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

# Blog settings
blog_name: digestion
blog_description: often an idea fascinates
permalink: /blog/:year/:title/

display_tags: ["games", "math", "code", "philosophy"]
display_categories: []