# Site settings
title: two_spoons
description: welcome to two_spoons! here you'll find articles about writing, casting, and coding.
baseurl: "/two_spoons_online" # the subpath of your site, e.g. /blog
url: "https://twobloodyspoons.github.io" # the base hostname & protocol for your site

# HTTPS enforcement
enforce_ssl: "twobloodyspoons.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Include files for processing
include:
  - _headers

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gemspec"
  - "*.gem"
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - venv/

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Categories
categories:
  - writing
  - casting
  - coding

# Site configuration
timezone: UTC
encoding: "utf-8"

# GitHub Pages / GitHub Actions compatibility
github: [metadata]